paths:
  model_dataframe: "./data/full_dataset.csv"
  mask_detection_model_path: "./model/model.h5"
  face_detection_model_path:
    model_file: "./model/opencv_face_detector_uint8.pb"
    model_config: "./model/opencv_face_detector.pbtxt"
  training_history_path: "./model/training_history.csv"

model:
  input_shape: [224, 224]
  target_encoder:
    mask: ["without_mask", "with_mask"]
  target: "mask_encoded"
  paths: "image_path"
  class_mode: "categorical"
  freeze_convolutional_layers: False
  batch_size: 32
  random_seed: 12345
  learning_rate: 0.01
  early_stopping_patience: 10
  lr_reducer_factor: 0.1
  lr_reducer_patience: 5
  min_lr: .000001

detector:
  running_on_pi: False
  resolution: [320, 240]
  view_frames: True
  api_url: http://192.168.15.10:8000/predict/
  message_delta_time_minutes: 30
  message: "PUT ON A MASK!!"
  detector_threshold: 0.5
